name: Build FMU using OpenModelica Script

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-fmu:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OpenModelica from official script
      run: |
        sudo apt update
        sudo apt install -y curl
        curl -fsSL https://raw.githubusercontent.com/OpenModelica/OpenModelica/master/scripts/install-linux.sh | bash

    - name: Build FMU
      run: |
        omc --version
        omc --emit-fmu=GridTiedMicrogridRLC.mo

    - name: Upload FMU
      uses: actions/upload-artifact@v4
      with:
        name: GridTiedMicrogridRLC-FMU
        path: GridTiedMicrogridRLC.fmu
