name: Build FMU using OpenModelica (No Docker)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-fmu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OpenModelica
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository -y ppa:openmodelica/ppa
        sudo apt update
        sudo apt install -y openmodelica

    - name: Build FMU
      run: |
        omc --version
        omc --emit-fmu=GridTiedMicrogridRLC.mo

    - name: Upload FMU
      uses: actions/upload-artifact@v4
      with:
        name: GridTiedMicrogridRLC-FMU
        path: GridTiedMicrogridRLC.fmu
