name: Build FMU using OpenModelica

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-fmu:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OpenModelica from official script
      run: |
        sudo apt update
        sudo apt install -y curl
        curl -fsSL https://raw.githubusercontent.com/OpenModelica/OpenModelica/master/scripts/install-linux.sh | bash

    - name: Debug omc location
      run: |
        echo "Searching for omc binary..."
        sudo find / -type f -name "omc" 2>/dev/null
        echo "Environment PATH: $PATH"
        which omc || echo "omc not found"

    - name: Locate and Run omc
      run: |
        # Find the actual path to omc
        OMC_PATH=$(sudo find / -type f -name "omc" 2>/dev/null | grep -m1 "bin/omc")
        if [ -z "$OMC_PATH" ]; then
          echo "❌ omc not found"
          exit 1
        fi
        echo "✅ omc found at: $OMC_PATH"

        # Add to PATH
        export PATH="$(dirname $OMC_PATH):$PATH"

        # Confirm and build FMU
        omc --version
        omc --emit-fmu=GridTiedMicrogridRLC.mo

    - name: Upload FMU
      uses: actions/upload-artifact@v4
      with:
        name: GridTiedMicrogridRLC-FMU
        path: GridTiedMicrogridRLC.fmu
