name: Build FMU

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-fmu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull OpenModelica from GitHub Container Registry
      run: docker pull ghcr.io/openmodelica/openmodelica:v1.22.2

    - name: Generate FMU
      run: |
        docker run --rm -v ${{ github.workspace }}:/mnt ghcr.io/openmodelica/openmodelica:v1.22.2 \
          omc --emit-fmu /mnt/GridTiedMicrogridRLC.mo

    - name: Upload FMU
      uses: actions/upload-artifact@v4
      with:
        name: GridTiedMicrogridRLC-FMU
        path: GridTiedMicrogridRLC.fmu
