name: Build FMU using OpenModelica

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-fmu:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OpenModelica (nightly build)
      run: |
        sudo apt update
        wget https://build.openmodelica.org/omc/builds/linux/nightly-builds/ubuntu-22.04/openmodelica_1.22.3~dev-1_amd64.deb
        sudo apt install -y ./openmodelica_1.22.3~dev-1_amd64.deb

    - name: Set PATH and Build FMU
      run: |
        export PATH="/usr/bin:/usr/local/bin:/usr/lib/x86_64-linux-gnu/openmodelica/bin:$PATH"
        omc --version || { echo "❌ omc not found in expected locations"; exit 1; }
        omc --emit-fmu=GridTiedMicrogridRLC.mo

    - name: Upload FMU
      uses: actions/upload-artifact@v4
      with:
        name: GridTiedMicrogridRLC-FMU
        path: GridTiedMicrogridRLC.fmu
