name: Build FMU using OpenModelica (Manual Install)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-fmu:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OpenModelica (manual install)
      run: |
        sudo apt update
        wget https://build.openmodelica.org/omc/builds/linux/releases/1.22.2/ubuntu-22.04/openmodelica_1.22.2-1_amd64.deb
        sudo apt install -y ./openmodelica_1.22.2-1_amd64.deb

    - name: Build FMU
      run: |
        omc --version
        omc --emit-fmu=GridTiedMicrogridRLC.mo

    - name: Upload FMU
      uses: actions/upload-artifact@v4
      with:
        name: GridTiedMicrogridRLC-FMU
        path: GridTiedMicrogridRLC.fmu
