name: Build FMU using public OMC image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-fmu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull public OpenModelica image
      run: docker pull openmodelica/omc

    - name: Generate FMU
      run: |
        docker run --rm -v ${{ github.workspace }}:/mnt openmodelica/omc \
          omc --emit-fmu=/mnt/GridTiedMicrogridRLC.mo

    - name: Upload FMU
      uses: actions/upload-artifact@v4
      with:
        name: GridTiedMicrogridRLC-FMU
        path: GridTiedMicrogridRLC.fmu
