name: Build FMU using OpenModelica

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-fmu:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common wget gnupg2

      - name: Add OpenModelica repository
        run: |
          # Add OpenModelica GPG key
          wget -q http://build.openmodelica.org/apt/openmodelica.asc -O - | sudo gpg --dearmor -o /usr/share/keyrings/openmodelica-keyring.gpg
          # Add OpenModelica stable repository for Ubuntu 22.04
          echo "deb [signed-by=/usr/share/keyrings/openmodelica-keyring.gpg] http://build.openmodelica.org/apt jammy stable" | sudo tee /etc/apt/sources.list.d/openmodelica.list
          sudo apt-get update

      - name: Install OpenModelica
        run: |
          sudo apt-get install -y openmodelica
          # Check available Modelica libraries
          apt-cache search omlib
          # Install all available OpenModelica libraries
          sudo apt-get install -y 'omlib-*' || echo "Some libraries may not be available, proceeding..."

      - name: Verify installation and build FMU
        run: |
          which omc
          omc --version
          # Ensure the .mo file exists
          ls -l GridTiedMicrogridRLC.mo
          # Check model file for errors
          omc +showErrorMessages GridTiedMicrogridRLC.mo || echo "Model check failed, see errors above"
          # Build FMU with detailed error output
          omc -f GridTiedMicrogridRLC.fmu +showErrorMessages GridTiedMicrogridRLC.mo || echo "FMU generation failed, see errors above"
          # Verify FMU was created
          ls -l GridTiedMicrogridRLC.fmu || echo "FMU file not found"

      - name: Upload FMU
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: GridTiedMicrogridRLC-FMU
          path: GridTiedMicrogridRLC.fmu
