name: Build FMU using OpenModelica

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-fmu:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common wget gnupg2 curl unzip

      - name: Add OpenModelica repository
        run: |
          # Add OpenModelica GPG key
          wget -q http://build.openmodelica.org/apt/openmodelica.asc -O - | sudo gpg --dearmor -o /usr/share/keyrings/openmodelica-keyring.gpg
          # Add OpenModelica stable repository for Ubuntu 22.04
          echo "deb [signed-by=/usr/share/keyrings/openmodelica-keyring.gpg] http://build.openmodelica.org/apt jammy stable" | sudo tee /etc/apt/sources.list.d/openmodelica.list
          sudo apt-get update

      - name: Install OpenModelica
        run: |
          sudo apt-get install -y openmodelica
          # Check available Modelica libraries
          apt-cache search omlib > omlib_list.txt
          cat omlib_list.txt
          # Install all available OpenModelica libraries
          sudo apt-get install -y 'omlib-*' || echo "Some libraries may not be available, proceeding..."

      - name: Install Modelica Standard Library
        run: |
          # Create library directory
          mkdir -p /home/runner/.openmodelica/libraries
          # Try installing Modelica 3.2.3 using omc
          echo 'installPackage(Modelica, "3.2.3", exactMatch=true);' > install_modelica.mos
          omc --silent +showErrorMessages install_modelica.mos > install_modelica.log 2>&1 || echo "Failed to install Modelica 3.2.3, trying fallback"
          cat install_modelica.log
          # Fallback: Try installing default Modelica version
          if ! grep -q "true" install_modelica.log; then
            echo 'installPackage(Modelica);' > install_modelica_default.mos
            omc --silent +showErrorMessages install_modelica_default.mos >> install_modelica.log 2>&1 || echo "Failed to install default Modelica version"
            cat install_modelica.log
          fi
          # Fallback: Manually download Modelica 3.2.3
          if ! grep -q "true" install_modelica.log; then
            echo "Manually downloading Modelica 3.2.3"
            curl -L -o modelica-3.2.3.zip https://github.com/modelica/ModelicaStandardLibrary/releases/download/v3.2.3/Modelica%203.2.3.zip
            # Verify download
            if [ -s modelica-3.2.3.zip ]; then
              unzip modelica-3.2.3.zip -d /home/runner/.openmodelica/libraries/
              mv /home/runner/.openmodelica/libraries/Modelica\ 3.2.3 /home/runner/.openmodelica/libraries/Modelica
              ls -l /home/runner/.openmodelica/libraries/
            else
              echo "Download failed: modelica-3.2.3.zip is empty or invalid"
              exit 1
            fi
          fi
          # Verify Modelica library availability
          omc +showErrorMessages -d=infoXmlOperations --version=3.2.3 Modelica > modelica_paths.txt 2>&1
          cat modelica_paths.txt

      - name: Verify installation and build FMU
        run: |
          # Verify OpenModelica installation
          which omc
          omc --version
          # Ensure the .mo file exists
          ls -l GridTiedMicrogridRLC.mo
          # Validate model file
          omc +showErrorMessages GridTiedMicrogridRLC.mo > model_check.log 2>&1 || echo "Model validation failed, see model_check.log"
          cat model_check.log
          # Build FMU with detailed logging
          omc -f GridTiedMicrogridRLC.fmu +showErrorMessages GridTiedMicrogridRLC.mo > fmu_build.log 2>&1 || echo "FMU generation failed, see fmu_build.log"
          cat fmu_build.log
          # Verify FMU was created
          ls -l GridTiedMicrogridRLC.fmu || echo "FMU file not found"

      - name: Upload logs for debugging
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Debug-Logs
          path: |
            omlib_list.txt
            modelica_paths.txt
            install_modelica.log
            model_check.log
            fmu_build.log

      - name: Upload FMU
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: GridTiedMicrogridRLC-FMU
          path: GridTiedMicrogridRLC.fmu
