name: Build FMU using OpenModelica

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-fmu:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common wget gnupg2

      - name: Add OpenModelica repository
        run: |
          # Add OpenModelica GPG key
          wget -q http://build.openmodelica.org/apt/openmodelica.asc -O - | sudo apt-key add -
          # Add OpenModelica stable repository for Ubuntu 22.04
          sudo sh -c 'echo "deb http://build.openmodelica.org/apt jammy stable" > /etc/apt/sources.list.d/openmodelica.list'
          sudo apt update

      - name: Install OpenModelica
        run: |
          sudo apt install -y openmodelica
          # Install additional libraries if needed
          sudo apt install -y omlib-modelica-3.2.3

      - name: Verify installation and build FMU
        run: |
          which omc
          omc --version
          omc +s GridTiedMicrogridRLC.mo -f GridTiedMicrogridRLC.fmu

      - name: Upload FMU
        uses: actions/upload-artifact@v4
        with:
          name: GridTiedMicrogridRLC-FMU
          path: GridTiedMicrogridRLC.fmu
